Repository backend20250319/BE09-Final-4team-BE, pull requests merged in 2025-08, with the labels that each got.

#7 엔티티 구조 최적화 및 불필요한 요소 제거
  user-service/src/main/java/com/hermes/userservice/config/DataInitializer.java
  user-service/src/main/java/com/hermes/userservice/entity/AuthorityLevel.java
  user-service/src/main/java/com/hermes/userservice/entity/EmployeeAssignment.java
  user-service/src/main/java/com/hermes/userservice/entity/EmployeeInfoChangeHistory.java
  user-service/src/main/java/com/hermes/userservice/entity/EmployeeInfoChangeType.java
  user-service/src/main/java/com/hermes/userservice/entity/EmploymentType.java
  user-service/src/main/java/com/hermes/userservice/entity/Job.java
  user-service/src/main/java/com/hermes/userservice/entity/Level.java
  user-service/src/main/java/com/hermes/userservice/entity/Organization.java
  user-service/src/main/java/com/hermes/userservice/entity/Position.java
  user-service/src/main/java/com/hermes/userservice/entity/Rank.java
  user-service/src/main/java/com/hermes/userservice/entity/User.java
  user-service/src/main/java/com/hermes/userservice/service/UserSecurityService.java
  user-service/src/main/java/com/hermes/userservice/service/UserService.java
Labels: 🔨 Refactor

#10 Feature/9 delete lockfeature
  user-service/src/main/java/com/hermes/userservice/entity/User.java
  user-service/src/main/java/com/hermes/userservice/service/UserSecurityService.java
Labels: 🐞 BugFix

#22 refactor: resolve error
  user-service/build.gradle
Labels: 🐞 BugFix

#19 user-serivce 내의 jwt 관련 코드 libs/jwt-common으로 이전
  gateway-server/src/main/java/com/hermes/gatewayserver/config/JwtConfig.java
  gateway-server/src/main/java/com/hermes/gatewayserver/filter/JwtAuthorizationFilter.java
  libs/jwt-common/src/main/java/com/hermes/jwt/JwtTokenProvider.java
  libs/jwt-common/src/main/java/com/hermes/jwt/controller/TokenManagementController.java
  libs/jwt-common/src/main/java/com/hermes/jwt/dto/ApiResponse.java
  libs/jwt-common/src/main/java/com/hermes/jwt/dto/RefreshRequest.java
  libs/jwt-common/src/main/java/com/hermes/jwt/dto/TokenRequest.java
  libs/jwt-common/src/main/java/com/hermes/jwt/dto/TokenResponse.java
  libs/jwt-common/src/main/java/com/hermes/jwt/service/JwtService.java
  libs/jwt-common/src/main/java/com/hermes/jwt/service/TokenBlacklistService.java
  user-service/src/main/java/com/hermes/userservice/config/JwtConfig.java
  user-service/src/main/java/com/hermes/userservice/config/SecurityConfig.java
  user-service/src/main/java/com/hermes/userservice/controller/AuthController.java
  user-service/src/main/java/com/hermes/userservice/entity/RefreshToken.java
  user-service/src/main/java/com/hermes/userservice/exception/GlobalExceptionHandler.java
  user-service/src/main/java/com/hermes/userservice/jwt/controller/TokenController.java
  user-service/src/main/java/com/hermes/userservice/jwt/dto/TokenRequest.java
  user-service/src/main/java/com/hermes/userservice/jwt/dto/TokenResponse.java
  user-service/src/main/java/com/hermes/userservice/jwt/service/JwtService.java
  user-service/src/main/java/com/hermes/userservice/repository/RefreshTokenRepository.java
  user-service/src/main/java/com/hermes/userservice/service/TokenBlacklistService.java
  user-service/src/main/java/com/hermes/userservice/service/UserService.java
Labels: ✨ Feature, 🔨 Refactor

#28 feat: 파일 업로드 스타터 구현
  communication-service/.gitattributes
  communication-service/.gitignore
  communication-service/build.gradle
  communication-service/gradle/wrapper/gradle-wrapper.jar
  communication-service/gradle/wrapper/gradle-wrapper.properties
  communication-service/gradlew
  communication-service/gradlew.bat
  communication-service/settings.gradle
  communication-service/src/main/java/com/hermes/communicationservice/CommunicationServiceApplication.java
  communication-service/src/main/java/com/hermes/communicationservice/FtpController.java
  communication-service/src/main/resources/application.yml
  libs/ftp-starter/.gitattributes
  libs/ftp-starter/.gitignore
  libs/ftp-starter/build.gradle
  libs/ftp-starter/gradle/wrapper/gradle-wrapper.jar
  libs/ftp-starter/gradle/wrapper/gradle-wrapper.properties
  libs/ftp-starter/gradlew
  libs/ftp-starter/gradlew.bat
  libs/ftp-starter/settings.gradle
  libs/ftp-starter/src/main/java/com/hermes/ftpstarter/config/FtpAutoConfiguration.java
  libs/ftp-starter/src/main/java/com/hermes/ftpstarter/dto/FtpResponseDto.java
  libs/ftp-starter/src/main/java/com/hermes/ftpstarter/properties/FtpProperties.java
  libs/ftp-starter/src/main/java/com/hermes/ftpstarter/service/FtpService.java
  libs/ftp-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  libs/ftp-starter/src/main/resources/application.yml
  settings.gradle
Labels: ✨ Feature

#50 Feature/42 auth context migration
  config-server/build.gradle
  config-server/src/main/resources/application.yml
  discovery-server/build.gradle
  gateway-server/build.gradle
  gateway-server/src/main/java/com/hermes/gatewayserver/GatewayServerApplication.java
  gateway-server/src/main/java/com/hermes/gatewayserver/filter/FilterProperties.java
  gateway-server/src/main/java/com/hermes/gatewayserver/filter/JwtAuthorizationFilter.java
  gateway-server/src/main/resources/application.yml
  user-service/build.gradle
  user-service/src/main/java/com/hermes/userservice/client/OrgServiceClientFallback.java
  user-service/src/main/java/com/hermes/userservice/config/DataInitializer.java
  user-service/src/main/java/com/hermes/userservice/config/JwtConfig.java
  user-service/src/main/java/com/hermes/userservice/config/PasswordEncoderConfig.java
  user-service/src/main/java/com/hermes/userservice/config/SecurityConfig.java
  user-service/src/main/java/com/hermes/userservice/controller/AuthController.java
  user-service/src/main/java/com/hermes/userservice/dto/CreateMemberRequest.java
  user-service/src/main/java/com/hermes/userservice/dto/LoginRequest.java
  user-service/src/main/java/com/hermes/userservice/dto/LoginResponse.java
  user-service/src/main/java/com/hermes/userservice/dto/RegisterRequest.java
  user-service/src/main/java/com/hermes/userservice/dto/RegisterResponse.java
  user-service/src/main/java/com/hermes/userservice/dto/UpdateMemberRequest.java
  user-service/src/main/java/com/hermes/userservice/entity/RefreshToken.java
  user-service/src/main/java/com/hermes/userservice/entity/User.java
  user-service/src/main/java/com/hermes/userservice/repository/RefreshTokenRepository.java
  user-service/src/main/java/com/hermes/userservice/service/TokenCleanupService.java
  user-service/src/main/java/com/hermes/userservice/service/UserService.java
  user-service/src/main/resources/application.yml
Labels: ✨ Feature

#57 Feature/user workpolicy api
  gateway-server/src/main/java/com/hermes/gatewayserver/GatewayServerApplication.java
  user-service/src/main/java/com/hermes/userservice/client/WorkPolicyServiceClient.java
  user-service/src/main/java/com/hermes/userservice/client/WorkPolicyServiceClientFallback.java
  user-service/src/main/java/com/hermes/userservice/controller/UserController.java
  user-service/src/main/java/com/hermes/userservice/entity/User.java
  user-service/src/main/java/com/hermes/userservice/service/UserService.java
  user-service/src/main/java/com/hermes/userservice/service/WorkPolicyIntegrationService.java
Labels: ✨ Feature

#61 사용자 API 구현 및 User - service 수정
  user-service/README_POSTMAN.md
  user-service/src/main/java/com/hermes/userservice/client/WorkPolicyServiceClient.java
  user-service/src/main/java/com/hermes/userservice/client/WorkPolicyServiceClientFallback.java
  user-service/src/main/java/com/hermes/userservice/controller/AuthController.java
  user-service/src/main/java/com/hermes/userservice/controller/UserController.java
  user-service/src/main/java/com/hermes/userservice/dto/LoginRequest.java
  user-service/src/main/java/com/hermes/userservice/dto/LoginRequestDto.java
  user-service/src/main/java/com/hermes/userservice/dto/UserCreateDto.java
  user-service/src/main/java/com/hermes/userservice/dto/UserDetailResponseDto.java
  user-service/src/main/java/com/hermes/userservice/dto/UserResponseDto.java
  user-service/src/main/java/com/hermes/userservice/dto/UserUpdateDto.java
  user-service/src/main/java/com/hermes/userservice/dto/workpolicy/AnnualLeaveRequestDto.java
  user-service/src/main/java/com/hermes/userservice/dto/workpolicy/AnnualLeaveResponseDto.java
  user-service/src/main/java/com/hermes/userservice/dto/workpolicy/WorkPolicyRequestDto.java
  user-service/src/main/java/com/hermes/userservice/dto/workpolicy/WorkPolicyResponseDto.java
  user-service/src/main/java/com/hermes/userservice/dto/workpolicy/WorkPolicyUpdateDto.java
  user-service/src/main/java/com/hermes/userservice/entity/User.java
  user-service/src/main/java/com/hermes/userservice/mapper/UserMapper.java
  user-service/src/main/java/com/hermes/userservice/service/UserSecurityService.java
  user-service/src/main/java/com/hermes/userservice/service/UserService.java
  user-service/src/main/java/com/hermes/userservice/service/WorkPolicyIntegrationService.java
Labels: ✨ Feature, 🔨 Refactor

#74 유저서비스 workPolicy API 네이밍 변경
  user-service/build.gradle
  user-service/src/main/java/com/hermes/userservice/client/WorkPolicyServiceClient.java
  user-service/src/main/java/com/hermes/userservice/dto/UserResponseDto.java
  user-service/src/main/java/com/hermes/userservice/mapper/UserMapper.java
  user-service/src/main/java/com/hermes/userservice/service/UserService.java
  user-service/src/main/java/com/hermes/userservice/service/WorkPolicyIntegrationService.java
Labels: 🐞 BugFix, 🔨 Refactor
