Repository backend20250319/BE09-Final-4team-BE, pull requests merged in 2025-09, with the labels that each got.

#111 RabbitMQ 기반 알림 구현 및 공지사항 생성 시 알림 발행 적용
  CLAUDE.md
  communication-service/build.gradle
  communication-service/src/main/java/com/hermes/communicationservice/CommunicationServiceApplication.java
  communication-service/src/main/java/com/hermes/communicationservice/announcement/controller/AnnouncementController.java
  communication-service/src/main/java/com/hermes/communicationservice/announcement/service/AnnouncementService.java
  communication-service/src/main/java/com/hermes/communicationservice/client/UserServiceClient.java
  communication-service/src/main/java/com/hermes/communicationservice/client/UserServiceClientFallback.java
  communication-service/src/main/java/com/hermes/communicationservice/client/dto/MainProfileResponseDto.java
  communication-service/src/main/java/com/hermes/communicationservice/comment/controller/CommentController.java
  communication-service/src/main/java/com/hermes/communicationservice/comment/dto/CommentCreateDto.java
  communication-service/src/main/java/com/hermes/communicationservice/comment/dto/CommentResponseDto.java
  communication-service/src/main/java/com/hermes/communicationservice/comment/dto/UserBasicInfo.java
  communication-service/src/main/java/com/hermes/communicationservice/comment/mapper/CommentMapper.java
  communication-service/src/main/java/com/hermes/communicationservice/comment/service/CommentService.java
  communication-service/src/main/java/com/hermes/communicationservice/notification/controller/NotificationController.java
  communication-service/src/main/java/com/hermes/communicationservice/notification/dto/CreateNotificationRequestDto.java
  communication-service/src/main/java/com/hermes/communicationservice/notification/dto/NotificationResponseDto.java
  communication-service/src/main/java/com/hermes/communicationservice/notification/entity/Notification.java
  communication-service/src/main/java/com/hermes/communicationservice/notification/exception/InvalidNotificationRequestException.java
  communication-service/src/main/java/com/hermes/communicationservice/notification/exception/NotificationAccessDeniedException.java
  communication-service/src/main/java/com/hermes/communicationservice/notification/exception/NotificationNotFoundException.java
  communication-service/src/main/java/com/hermes/communicationservice/notification/listener/NotificationEventListener.java
  communication-service/src/main/java/com/hermes/communicationservice/notification/repository/NotificationRepository.java
  communication-service/src/main/java/com/hermes/communicationservice/notification/service/NotificationService.java
  communication-service/src/main/resources/application.yml
  gateway-server/src/main/resources/application.yml
  libs/api-client/user-service-client/build.gradle
  libs/api-client/user-service-client/src/main/java/com/hermes/userserviceclient/client/UserServiceClient.java
  libs/api-client/user-service-client/src/main/java/com/hermes/userserviceclient/dto/UserDetailResponseDto.java
  libs/notification-starter/README.md
  libs/notification-starter/build.gradle
  libs/notification-starter/src/main/java/com/hermes/notification/config/NotificationAutoConfiguration.java
  libs/notification-starter/src/main/java/com/hermes/notification/dto/NotificationRequest.java
  libs/notification-starter/src/main/java/com/hermes/notification/dto/NotificationResponse.java
  libs/notification-starter/src/main/java/com/hermes/notification/enums/NotificationType.java
  libs/notification-starter/src/main/java/com/hermes/notification/event/NotificationEvent.java
  libs/notification-starter/src/main/java/com/hermes/notification/exception/NotificationPublishException.java
  libs/notification-starter/src/main/java/com/hermes/notification/exception/NotificationSendException.java
  libs/notification-starter/src/main/java/com/hermes/notification/publisher/NotificationPublisher.java
  libs/notification-starter/src/main/java/com/hermes/notification/sender/NotificationSender.java
  libs/notification-starter/src/main/java/com/hermes/notification/sender/RabbitNotificationSender.java
  libs/notification-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  settings.gradle
Labels: ✨ Feature

#120 feat(be): 출근 시간 한국 표준시(KST)로 표시하도록 설정
  attendance-service/src/main/resources/application.yml
Labels: 📃 Docs

#127 Feature/workpolicy api integration
  attendance-service/src/main/java/com/hermes/attendanceservice/controller/AttendanceController.java
  attendance-service/src/main/java/com/hermes/attendanceservice/controller/WorkScheduleController.java
  attendance-service/src/main/java/com/hermes/attendanceservice/dto/attendance/AttendanceResponse.java
  attendance-service/src/main/java/com/hermes/attendanceservice/dto/attendance/CheckInRequest.java
  attendance-service/src/main/java/com/hermes/attendanceservice/dto/attendance/CheckOutRequest.java
  attendance-service/src/main/java/com/hermes/attendanceservice/dto/leave/LeaveRequestResponseDto.java
  attendance-service/src/main/java/com/hermes/attendanceservice/dto/workpolicy/AnnualLeaveResponseDto.java
  attendance-service/src/main/java/com/hermes/attendanceservice/dto/workpolicy/WorkPolicyListResponseDto.java
  attendance-service/src/main/java/com/hermes/attendanceservice/dto/workpolicy/WorkPolicyResponseDto.java
  attendance-service/src/main/java/com/hermes/attendanceservice/dto/workschedule/AnnualLeaveResponseDto.java
  attendance-service/src/main/java/com/hermes/attendanceservice/dto/workschedule/ScheduleResponseDto.java
  attendance-service/src/main/java/com/hermes/attendanceservice/entity/attendance/Attendance.java
  attendance-service/src/main/java/com/hermes/attendanceservice/entity/leave/LeaveRequest.java
  attendance-service/src/main/java/com/hermes/attendanceservice/entity/workpolicy/AnnualLeave.java
  attendance-service/src/main/java/com/hermes/attendanceservice/entity/workpolicy/WorkPolicy.java
  attendance-service/src/main/java/com/hermes/attendanceservice/entity/workschedule/Schedule.java
  attendance-service/src/main/java/com/hermes/attendanceservice/entity/workschedule/ScheduleType.java
  attendance-service/src/main/java/com/hermes/attendanceservice/entity/workschedule/WorkTimeAdjustment.java
  attendance-service/src/main/java/com/hermes/attendanceservice/service/attendance/AttendanceService.java
  attendance-service/src/main/java/com/hermes/attendanceservice/service/attendance/AttendanceServiceImpl.java
  attendance-service/src/main/java/com/hermes/attendanceservice/service/workschedule/WorkScheduleService.java
Labels: ✨ Feature, 🔨 Refactor

#128 유저서비스 컨트롤러 개별 사용자 조회 엔드포인트 권한 제거
  user-service/src/main/java/com/hermes/userservice/controller/UserController.java
  user-service/src/main/java/com/hermes/userservice/dto/UserResponseDto.java
  user-service/src/main/java/com/hermes/userservice/mapper/UserMapper.java
  user-service/src/main/java/com/hermes/userservice/service/UserService.java
Labels: 🔨 Refactor

#133 Feature: 결재 서비스 사용자 경험 개선 (#81)
  CLAUDE.md
  approval-service/src/main/java/com/hermes/approvalservice/client/UserServiceClient.java
  approval-service/src/main/java/com/hermes/approvalservice/client/UserServiceClientFallback.java
  approval-service/src/main/java/com/hermes/approvalservice/client/dto/UserProfile.java
  approval-service/src/main/java/com/hermes/approvalservice/controller/ApprovalDocumentController.java
  approval-service/src/main/java/com/hermes/approvalservice/controller/DocumentCommentController.java
  approval-service/src/main/java/com/hermes/approvalservice/converter/ResponseConverter.java
  approval-service/src/main/java/com/hermes/approvalservice/dto/request/CreateDocumentRequest.java
  approval-service/src/main/java/com/hermes/approvalservice/dto/request/CreateTemplateRequest.java
  approval-service/src/main/java/com/hermes/approvalservice/dto/request/UpdateDocumentRequest.java
  approval-service/src/main/java/com/hermes/approvalservice/dto/request/UpdateTemplateRequest.java
  approval-service/src/main/java/com/hermes/approvalservice/dto/response/ApprovalTargetResponse.java
  approval-service/src/main/java/com/hermes/approvalservice/dto/response/DocumentActivityResponse.java
  approval-service/src/main/java/com/hermes/approvalservice/dto/response/DocumentCommentResponse.java
  approval-service/src/main/java/com/hermes/approvalservice/dto/response/DocumentResponse.java
  approval-service/src/main/java/com/hermes/approvalservice/dto/response/DocumentSummaryResponse.java
  approval-service/src/main/java/com/hermes/approvalservice/dto/response/TemplateResponse.java
  approval-service/src/main/java/com/hermes/approvalservice/dto/response/TemplateSummaryResponse.java
  approval-service/src/main/java/com/hermes/approvalservice/entity/ApprovalDocument.java
  approval-service/src/main/java/com/hermes/approvalservice/entity/DocumentTemplate.java
  approval-service/src/main/java/com/hermes/approvalservice/enums/ActivityType.java
  approval-service/src/main/java/com/hermes/approvalservice/enums/AttachmentUsageType.java
  approval-service/src/main/java/com/hermes/approvalservice/exception/GlobalExceptionHandler.java
  approval-service/src/main/java/com/hermes/approvalservice/repository/ApprovalDocumentRepository.java
  approval-service/src/main/java/com/hermes/approvalservice/service/ApprovalDocumentService.java
  approval-service/src/main/java/com/hermes/approvalservice/service/ApprovalProcessService.java
  approval-service/src/main/java/com/hermes/approvalservice/service/DocumentActivityService.java
  approval-service/src/main/java/com/hermes/approvalservice/service/DocumentPermissionService.java
  approval-service/src/main/java/com/hermes/approvalservice/service/DocumentTemplateService.java
  libs/auth-starter/build.gradle
  libs/auth-starter/src/main/java/com/hermes/auth/config/FeignConfig.java
  user-service/src/main/java/com/hermes/userservice/controller/UserController.java
  user-service/src/main/java/com/hermes/userservice/service/UserService.java
Labels: 🔨 Refactor

#134 입사일 기준 연차 자동 부여 시스템 구현
  user-service/src/main/java/com/hermes/userservice/client/WorkPolicyServiceClient.java
  user-service/src/main/java/com/hermes/userservice/client/WorkPolicyServiceClientFallback.java
  user-service/src/main/java/com/hermes/userservice/dto/workpolicy/AnnualLeaveResponseDto.java
  user-service/src/main/java/com/hermes/userservice/scheduler/VacationScheduler.java
  user-service/src/main/java/com/hermes/userservice/service/VacationService.java
  user-service/src/main/java/com/hermes/userservice/service/WorkPolicyIntegrationService.java
  user-service/src/main/java/com/hermes/userservice/util/CareerCalculator.java
Labels: ✨ Feature

#136 연차 일수 부여, 차감 및 조회 로직 생성
  attendance-service/src/main/java/com/hermes/attendanceservice/client/UserServiceClient.java
  attendance-service/src/main/java/com/hermes/attendanceservice/config/FeignClientConfig.java
  attendance-service/src/main/java/com/hermes/attendanceservice/config/SecurityConfig.java
  attendance-service/src/main/java/com/hermes/attendanceservice/controller/EmployeeLeaveBalanceController.java
  attendance-service/src/main/java/com/hermes/attendanceservice/dto/leave/EmployeeLeaveBalanceResponseDto.java
  attendance-service/src/main/java/com/hermes/attendanceservice/dto/leave/EmployeeLeaveBalanceSummaryDto.java
  attendance-service/src/main/java/com/hermes/attendanceservice/entity/leave/EmployeeLeaveBalance.java
  attendance-service/src/main/java/com/hermes/attendanceservice/repository/leave/EmployeeLeaveBalanceRepository.java
  attendance-service/src/main/java/com/hermes/attendanceservice/service/leave/EmployeeLeaveBalanceService.java
  attendance-service/src/main/java/com/hermes/attendanceservice/service/leave/EmployeeLeaveBalanceServiceImpl.java
  attendance-service/src/main/java/com/hermes/attendanceservice/service/leave/LeaveService.java
  attendance-service/src/main/java/com/hermes/attendanceservice/service/workschedule/WorkScheduleService.java
  attendance-service/src/main/resources/db/migration/V20250904__instant_utc_postgres.sql
Labels: ✨ Feature

#140 구성원 관리 시스템 전체 API 구현 및 연차 자동 부여 시스템
  gateway-server/src/main/resources/application.yml
  user-service/src/main/java/com/hermes/userservice/config/UserSecurityConfig.java
  user-service/src/main/java/com/hermes/userservice/controller/AuthController.java
  user-service/src/main/java/com/hermes/userservice/controller/TitleController.java
  user-service/src/main/java/com/hermes/userservice/dto/LoginResponse.java
  user-service/src/main/java/com/hermes/userservice/dto/LoginResult.java
  user-service/src/main/java/com/hermes/userservice/dto/MainProfileResponseDto.java
  user-service/src/main/java/com/hermes/userservice/dto/PasswordChangeRequestDto.java
  user-service/src/main/java/com/hermes/userservice/dto/UserCreateDto.java
  user-service/src/main/java/com/hermes/userservice/dto/UserResponseDto.java
  user-service/src/main/java/com/hermes/userservice/dto/UserUpdateDto.java
  user-service/src/main/java/com/hermes/userservice/dto/title/CreateJobRequest.java
  user-service/src/main/java/com/hermes/userservice/dto/title/CreatePositionRequest.java
  user-service/src/main/java/com/hermes/userservice/dto/title/CreateRankRequest.java
  user-service/src/main/java/com/hermes/userservice/dto/title/EmploymentTypeDto.java
  user-service/src/main/java/com/hermes/userservice/dto/title/JobDto.java
  user-service/src/main/java/com/hermes/userservice/dto/title/PositionDto.java
  user-service/src/main/java/com/hermes/userservice/dto/title/RankDto.java
  user-service/src/main/java/com/hermes/userservice/dto/title/UpdateJobRequest.java
  user-service/src/main/java/com/hermes/userservice/dto/title/UpdatePositionRequest.java
  user-service/src/main/java/com/hermes/userservice/dto/title/UpdateRankRequest.java
  user-service/src/main/java/com/hermes/userservice/entity/EmploymentType.java
  user-service/src/main/java/com/hermes/userservice/mapper/UserMapper.java
  user-service/src/main/java/com/hermes/userservice/repository/JobRepository.java
  user-service/src/main/java/com/hermes/userservice/repository/PositionRepository.java
  user-service/src/main/java/com/hermes/userservice/repository/RankRepository.java
  user-service/src/main/java/com/hermes/userservice/service/AuthService.java
  user-service/src/main/java/com/hermes/userservice/service/TitleService.java
  user-service/src/main/java/com/hermes/userservice/service/UserService.java
  user-service/src/main/java/com/hermes/userservice/validation/PasswordValidator.java
  user-service/src/main/java/com/hermes/userservice/validation/ValidPassword.java
  user-service/src/main/resources/application.yml
Labels: ✨ Feature

#142 Feature/add attendance and schedule
  attendance-service/README.md
  attendance-service/src/main/java/com/hermes/attendanceservice/aichat/config/AiChatProperties.java
  attendance-service/src/main/java/com/hermes/attendanceservice/aichat/controller/AiChatController.java
  attendance-service/src/main/java/com/hermes/attendanceservice/aichat/dto/ChatMessage.java
  attendance-service/src/main/java/com/hermes/attendanceservice/aichat/dto/ChatRequest.java
  attendance-service/src/main/java/com/hermes/attendanceservice/aichat/dto/ChatResponse.java
  attendance-service/src/main/java/com/hermes/attendanceservice/aichat/dto/CommandPayload.java
  attendance-service/src/main/java/com/hermes/attendanceservice/aichat/dto/CommandType.java
  attendance-service/src/main/java/com/hermes/attendanceservice/aichat/service/AiChatService.java
  attendance-service/src/main/java/com/hermes/attendanceservice/controller/WorkMonitorController.java
  attendance-service/src/main/java/com/hermes/attendanceservice/entity/workmonitor/WorkMonitor.java
  attendance-service/src/main/java/com/hermes/attendanceservice/entity/workschedule/ScheduleType.java
  attendance-service/src/main/java/com/hermes/attendanceservice/service/attendance/AttendanceService.java
  attendance-service/src/main/java/com/hermes/attendanceservice/service/attendance/AttendanceServiceImpl.java
  attendance-service/src/main/java/com/hermes/attendanceservice/service/workmonitor/WorkMonitorService.java
  attendance-service/src/main/java/com/hermes/attendanceservice/service/workschedule/WorkScheduleService.java
  attendance-service/src/main/resources/db/migration/V20250905__work_monitor_timestamps.sql
  gateway-server/src/main/resources/application.yml
Labels: ✨ Feature
